### ISSUE TITLE
Highlighting on search results is not visible

### ISSUE THREAD

**Issue by kbravh** [sdras/inbedby7pm#10]
Hey Sarah, the new theme is great! 

I noticed an issue with the search results highlight color, it's not very visible against the background. Here's a comparison against Night Owl: 

![In Bed By 7pm search](https://user-images.githubusercontent.com/30562119/94514352-9511a700-01e6-11eb-9ded-3a1c2186ef9e.png)
![night owl search](https://user-images.githubusercontent.com/30562119/94514354-95aa3d80-01e6-11eb-974c-ca5f366e8f04.png)

This is on version 0.3.1 of the theme.

**Comment by sdras** [comment]
Hey @kbravh I worked on a lot of highlight stuff in the last two versions, can you please update? Feel free to reopen if you aren't satisfied.

**Comment by kbravh** [comment]
@sdras These screenshots are from the latest version, it looks like it's from lines 85-86 of `in-bed-by-7.json`.

```js
"editor.findMatchBackground": "#16192333",
"editor.findMatchHighlightBackground": "#16192333",
```
This color differs only slightly in opacity from the background color on line 92:

```js
"editor.rangeHighlightBackground": "#161923dd",
```
