### ISSUE TITLE
No border around menu dropdowns

### ISSUE THREAD

**Issue by MarcelloTheArcane** [sdras/inbedby7pm#11]
In some places there is a black (ish?) border.  It would be great if there was one around the dropdowns for `File`, `Edit`, etc.

![image](https://user-images.githubusercontent.com/21159570/94526878-15a7c600-022e-11eb-9141-ed0da7971139.png)

While I think about it, it would be nice if there was a border down the side bar too 😁

**Comment by sdras** [comment]
Yeah, I like this as a preference, to not have borders here, feels like a lot of noise to me. I'll do what I did with Night Owl, where I update the readme with workplace settings you can set if you like the borders. Thanks!

**Comment by MarcelloTheArcane** [comment]
That's fine, it's your design after all!  Thanks a lot 😁
