### ISSUE TITLE
File title when focused on different pane.

### ISSUE THREAD

**Issue by davidwessman** [sdras/inbedby7pm#19]
Hello again, this is seen on **version 0.3.3**.

When I split my editor side-by-side the contrast of the other file-tabs changes.

When I focus on `.vscodeignore` I can still read the filename of `settings.json`:
<img width="1342" alt="Screenshot 2020-10-04 at 08 50 22" src="https://user-images.githubusercontent.com/6763624/95009014-ea9ee700-061e-11eb-9c5a-1321b1c626ee.png">

When I focus on the other pane on `CHANGELOG.md` I cannot read `settings.json` but only `.vscodeignore`:
<img width="1339" alt="Screenshot 2020-10-04 at 08 50 30" src="https://user-images.githubusercontent.com/6763624/95009015-eb377d80-061e-11eb-8fca-8939f91569b9.png">

I could not find which color setting affects this, please let me know if I can help.

**Comment by mjcrouch** [comment]
I came here to raise the same issue. 

I've set the following in my json:

```
    "workbench.colorCustomizations": {
        "[In Bed by 7pm]": {
            "tab.unfocusedInactiveForeground": "#cccccc"
        }
    }
```

**Comment by jvik** [comment]
Which version of the theme are you on @davidwessman ? I believe this should be fixed in 0.3.3

**Comment by mjcrouch** [comment]
I don't think it is - I'm on 0.3.3 and it looks like the screenshot without my customisation.

To make absolutely sure I downloaded the 0.3.3 vsix from the marketplace, changed it to a zip file, and it contains the following,

```
    "tab.unfocusedActiveBorder": "#17181d",
```

i.e. the old value

**Comment by sdras** [comment]
This should be fixed now! Please feel free to reopen if not.
