### ISSUE TITLE
Inline code in markdown has general text colour

### ISSUE THREAD

**Issue by cartant** [sdras/inbedby7pm#5]
Thanks for the new theme, Sarah.

I noticed that inline code within markdown paragraphs does not appear to be shown in a different colour - as it is in Night Owl.

It looks like this:

<img width="270" alt="inbedby7" src="https://user-images.githubusercontent.com/3878593/94377134-74077280-0162-11eb-8d85-4d64a1419fb5.PNG">

Whereas in Night Owl it looks like this:

<img width="268" alt="nightowl" src="https://user-images.githubusercontent.com/3878593/94377133-6fdb5500-0162-11eb-98f5-cc06d5a6ebb9.PNG">

Whether or not this is intentional, IDK. I just thought I'd bring it to your attention in case it isn't.

**Comment by sdras** [comment]
Oh great catch, yes I'll be sure to update that in the next release!

**Comment by sdras** [comment]
Fixed!
