### ISSUE TITLE
Welcome screen text colour issue

### ISSUE THREAD

**Issue by sasi-wic** [sdras/inbedby7pm#6]
Great theme. Thank you for the effort.

When I open code the welcome screen text on right has white background. I think it is supposed to have same dark background.

<img width="1277" alt="Screenshot 2020-09-28 at 8 46 43 AM" src="https://user-images.githubusercontent.com/58414259/94399332-ca85a880-0184-11eb-972f-1c045fd717e6.png">

**Comment by sdras** [comment]
yeesh, that's bad! Sorry about that, I'll take care of it soon.

**Comment by MarcelloTheArcane** [comment]
It's here: https://github.com/sdras/inbedby7pm/blob/master/themes/in-bed-by-7.json#L198-L199
