### ISSUE TITLE
No extensions found!

### ISSUE THREAD

**Issue by MarcelloTheArcane** [sdras/inbedby7pm#7]
This extension looks great! Unfortunately my VS code can't find it when I search for `inbedby7`.

Using some incredible sleuthing techniques I have discovered it is found by searching `In bed by 7pm` or `sdras`.

![Not found](https://user-images.githubusercontent.com/21159570/94430766-54853f80-018c-11eb-9c9c-74292ecfb4d9.png)

![Found](https://user-images.githubusercontent.com/21159570/94430970-9dd58f00-018c-11eb-8f14-eb1a7c1fa391.png)

**Comment by sdras** [comment]
Thanks! Updated the readme to reflect this.
