### ISSUE TITLE
Unselected tab font color blends with background

### ISSUE THREAD

**Issue by madisonbullard** [sdras/inbedby7pm#8]
![image](https://user-images.githubusercontent.com/4810002/94441382-afa93900-0170-11eb-811c-0d5397c5e408.png)
vscode 1.49.2
mac osx 10.15.5

Wanted to quickly point this out. Haven't had a chance to debug myself, and might not get to it, so there's certainly a chance this is an issue with my config and not the theme.

Thank you for continuing to produce excellent themes! I have been using Night Owl for the past couple years and have really enjoyed it.

**Comment by madisonbullard** [comment]
Nevermind, issue on my end. Closing.

**Comment by dawneraq** [comment]
@madisonbullard What was your issue? I'm seeing the same thing too. (macOS 10.15.1)

![image](https://user-images.githubusercontent.com/9038965/94470463-94dcc180-017c-11eb-8d5c-867f23b982c8.png)

**Comment by madisonbullard** [comment]
@dawneraq I ended up making a few changes to the theme to address this issue + a few others. Details here: https://github.com/sdras/inbedby7pm/issues/21
